import { Glob } from "bun";
import { join, relative, dirname, extname } from "node:path";
import { writeFile, mkdir } from "node:fs/promises";

export async function generateTypes(options: { dir: string; output: string }) {
	const glob = new Glob("**/*.ts");
	const files: string[] = [];

	for await (const path of glob.scan({ cwd: options.dir, absolute: false })) {
		if (path.endsWith(".d.ts")) continue;
		files.push(path);
	}

	// Sort for stable output
	files.sort();

	const outputDir = dirname(options.output);
	const imports: string[] = [];
	const typeIds: string[] = [];

	files.forEach((file, index) => {
		const typeId = `Route${index}`;
		const absoluteRoutePath = join(options.dir, file);
		const absoluteOutputPath = options.output;

		let relativeImportPath = relative(
			dirname(absoluteOutputPath),
			absoluteRoutePath,
		);

		if (!relativeImportPath.startsWith(".")) {
			relativeImportPath = `./${relativeImportPath}`;
		}

		const ext = extname(relativeImportPath);
		relativeImportPath = relativeImportPath.substring(
			0,
			relativeImportPath.length - ext.length,
		);

		imports.push(`import type ${typeId} from "${relativeImportPath}";`);
		typeIds.push(typeId);
	});

	const content = `/* eslint-disable */
// @ts-nocheck
// This file is generated by elysia-atlas.
// Do not edit this file manually.

import type { Elysia } from "elysia";
${imports.join("\n")}

export type AutoloadedRoutes = Elysia
${typeIds.map((id) => `    .Use<typeof ${id}>`).join("\n")};
`;

	await mkdir(outputDir, { recursive: true });
	await writeFile(options.output, content);
}
