import { mkdirSync, writeFileSync } from "node:fs";
import * as p from "node:path";
import { globSync } from "glob";

const normalizeSeparators = (value: string) => value.replace(/\\/g, "/");

const isIntercept = (normalized: string) =>
	normalized === "intercept.ts" || normalized.endsWith("/intercept.ts");

export const toTypeImportPath = (output: string, dir: string, file: string) => {
	let relativeImportPath = p.relative(p.dirname(output), p.join(dir, file));
	relativeImportPath = normalizeSeparators(relativeImportPath);

	if (!relativeImportPath.startsWith(".")) {
		relativeImportPath = `./${relativeImportPath}`;
	}

	return relativeImportPath.substring(
		0,
		relativeImportPath.length - p.extname(relativeImportPath).length,
	);
};

export const toRouteLiteral = (filePath: string, prefix = "/") =>
	p.posix
		.join(normalizeSeparators(prefix), normalizeSeparators(filePath))
		.replace(/\/index\.ts$|\.ts$/, "")
		.replace(/\[([^\]]+)\]/g, ":$1");

export async function generateTypes(options: {
	dir: string;
	output: string;
	prefix?: string;
}) {
	const allFiles = globSync("**/*.ts", { cwd: options.dir });
	const files: string[] = [];

	for (const path of allFiles) {
		if (path.endsWith(".d.ts")) continue;
		const normalized = normalizeSeparators(path);
		if (isIntercept(normalized)) continue;
		files.push(path);
	}

	files.sort();

	const imports: string[] = [];
	const typeIds: [string, string][] = [];

	files.forEach((file, index) => {
		const typeId = `Route${index}`;
		const relativeImportPath = toTypeImportPath(
			options.output,
			options.dir,
			file,
		);

		imports.push(`import type ${typeId} from "${relativeImportPath}";`);
		typeIds.push([
			typeId,
			toRouteLiteral(file, options.prefix ?? "/"),
		] as const);
	});

	mkdirSync(p.dirname(options.output), { recursive: true });
	const autoloadedImportLine = typeIds.length
		? `import type { WithBasePath } from "elysia-atlas/types";`
		: `import type Elysia from "elysia";`;

	const autoloadedRoutesType =
		typeIds.length === 0
			? " Elysia"
			: `\n\t& ${typeIds
					.map(
						([id, path]) => `WithBasePath<ReturnType<typeof ${id}>, "${path}">`,
					)
					.join("\n\t& ")}`;

	writeFileSync(
		options.output,
		`/**
 * This file is auto-generated by elysia-atlas.
 * Do not edit this file manually — your changes will be overwritten.
 * Run your type generation command to regenerate this file.
 */
/* eslint-disable */
// @ts-nocheck
${autoloadedImportLine}
${imports.join("\n")}

export type AutoloadedRoutes =${autoloadedRoutesType};
`,
	);
}
